In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

A1. List cannot be instantiated. ArrayList can be instantiated. List interface is used to create a list of elements(objects) that are associated with their index numbers. ArrayList class is used to create a dynamic array that contains objects.

In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
list_

['1', '2', '3', '4', '5']

In [4]:
array_list.dtype

dtype('<U1')

In [5]:
list_.dtype

AttributeError: 'list' object has no attribute 'dtype'

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [7]:
array_list
print("Original list is : " + str(array_list))

res = True
for ele in array_list:
    if not isinstance(ele, type(array_list[0])):
        res = False
        break
print("All elements have same type : " + str(res))

Original list is : ['1' '2' '3' '4' '5']
All elements have same type : True


In [9]:
list_
print("Original list is : " + str(list_))

res = True
for ele in list_:
    if not isinstance(ele, type(list_[0])):
        res = False
        break
print("All elements have same type : " + str(res))

Original list is : ['1', '2', '3', '4', '5']
All elements have same type : True


Q3. Considering the following changes in the variable, array_list:

In [10]:
array_list = np.array(object = list_, dtype = int)

In [11]:
array_list

array([1, 2, 3, 4, 5])

In [12]:
list_

['1', '2', '3', '4', '5']

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [13]:
type(array_list)

numpy.ndarray

In [14]:
type(list_)

list

In [15]:
array_list
print("Original list is : " + str(array_list))

res = True
for ele in array_list:
    if not isinstance(ele, type(array_list[0])):
        res = False
        break
print("All elements have same type : " + str(res))

Original list is : [1 2 3 4 5]
All elements have same type : True


In [16]:
list_
print("Original list is : " + str(list_))

res = True
for ele in list_:
    if not isinstance(ele, type(list_[0])):
        res = False
        break
print("All elements have same type : " + str(res))

Original list is : ['1', '2', '3', '4', '5']
All elements have same type : True


In [17]:
#Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
- (i) shape
- (ii) size

In [18]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [23]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
- [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
- [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [30]:
#First Method
import numpy.matlib as nm
nm.eye(5,5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [29]:
#Second Method
array_q6=np.identity(5)
print('5x5 matrix:')
print(array_q6)

5x5 matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
